export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
    public status: number = 400,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export enum ErrorCode {
  // Auth
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  CHALLENGE_FAILED = 'CHALLENGE_FAILED',

  // Player
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  PLAYER_EXISTS = 'PLAYER_EXISTS',

  // Session
  NO_ACTIVE_SESSION = 'NO_ACTIVE_SESSION',
  SESSION_ALREADY_ACTIVE = 'SESSION_ALREADY_ACTIVE',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',

  // Trading
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  MAX_POSITIONS_REACHED = 'MAX_POSITIONS_REACHED',
  POSITION_NOT_FOUND = 'POSITION_NOT_FOUND',
  POSITION_NOT_OPEN = 'POSITION_NOT_OPEN',
  INVALID_LEVERAGE = 'INVALID_LEVERAGE',
  LEVERAGE_NOT_UNLOCKED = 'LEVERAGE_NOT_UNLOCKED',
  INVALID_MARGIN = 'INVALID_MARGIN',
  INVALID_ASSET = 'INVALID_ASSET',
  PRICE_UNAVAILABLE = 'PRICE_UNAVAILABLE',

  // Options
  MAX_OPTIONS_REACHED = 'MAX_OPTIONS_REACHED',
  INVALID_STRIKE = 'INVALID_STRIKE',
  INVALID_EXPIRY = 'INVALID_EXPIRY',

  // Proof
  SESSION_NOT_ENDED = 'SESSION_NOT_ENDED',
  PROOF_ALREADY_EXISTS = 'PROOF_ALREADY_EXISTS',
  PROOF_NOT_FOUND = 'PROOF_NOT_FOUND',

  // Badge
  BADGE_NOT_ELIGIBLE = 'BADGE_NOT_ELIGIBLE',
  BADGE_PROOF_FAILED = 'BADGE_PROOF_FAILED',
  BADGE_ALREADY_MINTED = 'BADGE_ALREADY_MINTED',

  // Education
  CHALLENGE_NOT_FOUND = 'CHALLENGE_NOT_FOUND',
  CHALLENGE_EXPIRED = 'CHALLENGE_EXPIRED',
  PATTERN_NOT_FOUND = 'PATTERN_NOT_FOUND',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
